import { CommonModule } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AdminService } from '../../core/services/admin.service';
import { PropertySubmission, SubmissionStatus } from '../../shared/models/admin.model';

@Component({
  selector: 'app-admin-submissions',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section>
      <header class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold uppercase tracking-[0.2em] text-rheo-muted">Soumissions de biens</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Vérifier avant de publier.</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-rheo-muted">Examinez les photos, les documents et gardez une trace de chaque décision.</p></div><div class="rounded-xl border border-[#e1e5dc] bg-white px-4 py-3 text-sm"><span class="font-semibold">{{ admin.stats().pendingSubmissions }}</span> <span class="text-rheo-muted">à vérifier</span></div></header>
      <div class="mt-8 grid gap-6 xl:grid-cols-[1.05fr_0.95fr]"><section class="overflow-hidden rounded-2xl border border-[#e4e6e1] bg-white"><div class="flex items-center justify-between border-b border-[#edf0eb] px-5 py-4 sm:px-6"><div class="flex flex-wrap gap-2"><button type="button" class="rounded-full px-3 py-2 text-xs font-semibold" [class]="filter() === 'all' ? 'bg-rheo-dark text-white' : 'bg-[#f3f5f1] text-rheo-muted'" (click)="filter.set('all')">Toutes</button><button type="button" class="rounded-full px-3 py-2 text-xs font-semibold" [class]="filter() === 'en attente' ? 'bg-rheo-dark text-white' : 'bg-[#f3f5f1] text-rheo-muted'" (click)="filter.set('en attente')">À vérifier</button><button type="button" class="rounded-full px-3 py-2 text-xs font-semibold" [class]="filter() === 'informations requises' ? 'bg-rheo-dark text-white' : 'bg-[#f3f5f1] text-rheo-muted'" (click)="filter.set('informations requises')">Précisions</button></div><span class="text-xs text-rheo-muted">{{ filtered().length }}</span></div><div class="divide-y divide-[#edf0eb]">@for (submission of filtered(); track submission.id) {<button type="button" class="flex w-full items-center gap-4 px-5 py-5 text-left transition hover:bg-[#fafbf9] sm:px-6" [class.bg-[#f8fbe9]]="selectedId() === submission.id" (click)="select(submission)"><div class="grid size-14 shrink-0 grid-cols-2 gap-1 overflow-hidden rounded-xl bg-[#edf0eb]">@for (photo of submission.photos.slice(0, 4); track photo) {<img [src]="photo" alt="" class="h-full w-full object-cover">}</div><span class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ submission.title }}</strong><span class="mt-1 block truncate text-xs text-rheo-muted">{{ submission.ownerName }} · {{ submission.city }}</span><span class="mt-2 block text-xs text-[#7a8375]">{{ submission.submittedAt | date:'dd MMM yyyy' }}</span></span><span class="shrink-0 rounded-full px-3 py-1 text-[11px] font-semibold" [class]="statusClass(submission.status)">{{ submission.status }}</span></button>} @empty {<div class="p-10 text-center text-sm text-rheo-muted">Aucune soumission pour ce filtre.</div>}</div></section>
      @if (selectedSubmission(); as submission) {<aside class="rounded-2xl border border-[#e4e6e1] bg-white p-5 sm:p-6"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-rheo-muted">Dossier de soumission</p><h2 class="mt-2 text-xl font-semibold">{{ submission.title }}</h2><p class="mt-1 text-sm text-rheo-muted">{{ submission.city }} · {{ submission.address }}</p></div><span class="rounded-full px-3 py-1 text-[11px] font-semibold" [class]="statusClass(submission.status)">{{ submission.status }}</span></div><p class="mt-5 rounded-xl bg-[#f6f7f4] px-4 py-3 text-sm leading-6 text-[#646d61]">{{ submission.description }}</p><div class="mt-6 grid grid-cols-3 gap-2">@for (photo of submission.photos; track photo) {<img [src]="photo" alt="Photo soumise" class="aspect-square w-full rounded-xl object-cover">}</div>@if (submission.status === 'en attente' || submission.status === 'informations requises') {<div class="mt-6 grid gap-3"><button type="button" class="h-11 rounded-xl bg-rheo-accent text-sm font-bold" (click)="accept(submission)">Valider et publier</button><textarea [(ngModel)]="rejectionReason" rows="3" class="w-full resize-none rounded-xl border border-[#dfe3dc] px-3 py-3 text-sm" placeholder="Message à transmettre"></textarea><button type="button" class="h-11 rounded-xl border border-[#d7b66d] text-sm font-semibold text-[#8d6200]" (click)="requestDetails(submission)">Demander des précisions</button><button type="button" class="h-11 rounded-xl border border-[#e4b7b7] text-sm font-semibold text-[#b42318]" (click)="reject(submission)">Refuser</button></div>} @if (submission.status === 'publiée') {<div class="mt-6 rounded-xl bg-[#edf5d6] px-4 py-3 text-sm font-semibold text-[#657b18]">Cette soumission est devenue une annonce publiée.</div>}</aside>} @else {<aside class="flex min-h-[420px] items-center justify-center rounded-2xl border border-dashed border-[#d5dbd0] bg-white p-8 text-center">Sélectionnez un dossier.</aside>}
      </div>
    </section>
  `,
})
export class AdminSubmissionsPage {
  protected readonly admin = inject(AdminService);
  protected readonly filter = signal<'all' | SubmissionStatus>('all');
  protected readonly selectedId = signal('');
  protected rejectionReason = '';
  protected readonly filtered = computed(() => this.filter() === 'all' ? this.admin.submissions() : this.admin.submissions().filter((submission) => submission.status === this.filter()));
  protected readonly selectedSubmission = computed(() => this.admin.submissions().find((submission) => submission.id === this.selectedId()) ?? null);

  protected select(submission: PropertySubmission): void { this.selectedId.set(submission.id); this.rejectionReason = submission.rejectionReason; }
  protected async accept(submission: PropertySubmission): Promise<void> { await this.admin.decideSubmission(submission, 'approve'); }
  protected async reject(submission: PropertySubmission): Promise<void> { if (!this.rejectionReason.trim()) return; await this.admin.decideSubmission(submission, 'reject', this.rejectionReason.trim()); }
  protected async requestDetails(submission: PropertySubmission): Promise<void> { if (!this.rejectionReason.trim()) return; await this.admin.decideSubmission(submission, 'request_details', this.rejectionReason.trim()); }
  protected statusClass(status: SubmissionStatus): string { return status === 'refusée' ? 'bg-[#fff0f0] text-[#b42318]' : status === 'en attente' ? 'bg-[#fff4d9] text-[#946200]' : 'bg-[#edf5d6] text-[#657b18]'; }
}
