import { CommonModule } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AdminService } from '../../core/services/admin.service';
import { ADMIN_REQUEST_STATUSES, ADMIN_SERVICE_TYPES } from '../../shared/models/admin.model';
import { REQUEST_STATUS_LABELS, RequestStatus, SERVICE_TYPE_LABELS, ServiceType } from '../../shared/models/service-request.model';

@Component({
  selector: 'app-admin-services',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section>
      <header class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold uppercase tracking-[0.2em] text-rheo-muted">Demandes de services</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Chaque demande, bien orientée.</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-rheo-muted">Filtrez par service, assignez un partenaire et préparez la prochaine notification client.</p></div><div class="rounded-xl border border-[#e1e5dc] bg-white px-4 py-3 text-sm"><span class="font-semibold">{{ filteredRequests().length }}</span> <span class="text-rheo-muted">dossier(s)</span></div></header>
      <div class="mt-8 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><section class="overflow-hidden rounded-2xl border border-[#e4e6e1] bg-white"><div class="flex flex-wrap items-center gap-2 border-b border-[#edf0eb] px-5 py-4 sm:px-6"><select [ngModel]="filterType()" (ngModelChange)="filterType.set($event)" class="h-10 rounded-xl border border-[#dfe3dc] bg-white px-3 text-xs font-semibold outline-none"><option value="all">Tous les services</option>@for (type of serviceTypes; track type) {<option [value]="type">{{ SERVICE_TYPE_LABELS[type] }}</option>}</select><select [ngModel]="filterStatus()" (ngModelChange)="filterStatus.set($event)" class="h-10 rounded-xl border border-[#dfe3dc] bg-white px-3 text-xs font-semibold outline-none"><option value="all">Tous les statuts</option>@for (status of statuses; track status) {<option [value]="status">{{ REQUEST_STATUS_LABELS[status] }}</option>}</select><span class="ml-auto text-xs text-rheo-muted">{{ filteredRequests().length }} résultat(s)</span></div><div class="divide-y divide-[#edf0eb]">@for (request of filteredRequests(); track request.id) {<button type="button" class="w-full px-5 py-5 text-left transition hover:bg-[#fafbf9] sm:px-6" [class.bg-[#f8fbe9]]="selectedId() === request.id" (click)="select(request)"><div class="flex items-start gap-4"><span class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-[#eef2e9] text-lg">{{ serviceIcon(request.serviceType) }}</span><span class="min-w-0 flex-1"><span class="flex flex-wrap items-center gap-2"><strong class="truncate text-sm">{{ request.description }}</strong><span class="rounded-full bg-[#f1f3ef] px-2 py-1 text-[10px] font-semibold text-[#667064]">{{ SERVICE_TYPE_LABELS[request.serviceType] }}</span></span><span class="mt-2 block text-xs text-rheo-muted">{{ request.clientName }} · {{ request.createdAt | date:'dd MMM yyyy' }}</span></span><span class="hidden rounded-full px-3 py-1 text-[11px] font-semibold sm:inline-flex" [class]="statusClass(request.status)">{{ request.status }}</span></div></button>} @empty {<div class="p-10 text-center text-sm text-rheo-muted">Aucune demande pour ces filtres.</div>}</div></section>
      @if (selectedRequest(); as request) {<aside class="rounded-2xl border border-[#e4e6e1] bg-white p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-rheo-muted">Détail demande</p><h2 class="mt-2 text-xl font-semibold">{{ request.description }}</h2></div><span class="rounded-full px-3 py-1 text-[11px] font-semibold" [class]="statusClass(request.status)">{{ request.status }}</span></div><div class="mt-6 grid gap-3 rounded-2xl bg-[#f6f7f4] p-4 text-sm"><div class="flex justify-between gap-3"><span class="text-rheo-muted">Demandeur</span><strong>{{ request.clientName }}</strong></div><div class="flex justify-between gap-3"><span class="text-rheo-muted">Email</span><strong class="truncate">{{ request.clientEmail }}</strong></div><div class="flex justify-between gap-3"><span class="text-rheo-muted">Téléphone</span><strong>{{ request.clientPhone }}</strong></div>@if (request.propertyId) {<div class="flex justify-between gap-3"><span class="text-rheo-muted">Annonce liée</span><strong>{{ request.propertyId }}</strong></div>}</div><div class="mt-6 grid gap-3"><label class="text-xs font-semibold text-rheo-muted">Statut<select [(ngModel)]="draftStatus" class="mt-2 h-11 w-full rounded-xl border border-[#dfe3dc] bg-white px-3 text-sm outline-none"><option value="reçue">Reçue</option><option value="en traitement">En traitement</option><option value="assignée">Assignée</option><option value="terminée">Terminée</option><option value="annulée">Annulée</option></select></label><label class="text-xs font-semibold text-rheo-muted">Partenaire assigné<input [(ngModel)]="draftAssigned" class="mt-2 h-11 w-full rounded-xl border border-[#dfe3dc] bg-white px-3 text-sm outline-none" placeholder="Nom ou identifiant du partenaire"></label><label class="text-xs font-semibold text-rheo-muted">Note interne<textarea [(ngModel)]="draftNotes" rows="4" class="mt-2 w-full resize-none rounded-xl border border-[#dfe3dc] bg-white px-3 py-3 text-sm outline-none" placeholder="Ajouter une note pour l’équipe..."></textarea></label><button type="button" class="h-11 rounded-xl bg-rheo-accent text-sm font-bold hover:bg-rheo-accent-hover" (click)="save(request)">Enregistrer le dossier</button><button type="button" class="h-11 rounded-xl border border-[#dfe3dc] text-sm font-semibold hover:bg-[#f6f7f4]" (click)="prepareNotification(request)">{{ request.notificationPrepared ? 'Notification préparée ✓' : 'Préparer la notification utilisateur' }}</button></div></aside>} @else {<aside class="flex min-h-[360px] items-center justify-center rounded-2xl border border-dashed border-[#d5dbd0] bg-white p-8 text-center"><div><span class="text-4xl">▣</span><h2 class="mt-4 font-semibold">Sélectionnez une demande</h2><p class="mt-2 max-w-xs text-sm leading-6 text-rheo-muted">Le détail, le partenaire et les notes internes seront accessibles ici.</p></div></aside>}
      </div>
    </section>
  `,
})
export class AdminServicesPage {
  protected readonly admin = inject(AdminService);
  protected readonly serviceTypes = ADMIN_SERVICE_TYPES;
  protected readonly statuses = ADMIN_REQUEST_STATUSES;
  protected readonly SERVICE_TYPE_LABELS = SERVICE_TYPE_LABELS;
  protected readonly REQUEST_STATUS_LABELS = REQUEST_STATUS_LABELS;
  protected readonly filterType = signal<'all' | ServiceType>('all');
  protected readonly filterStatus = signal<'all' | RequestStatus>('all');
  protected readonly selectedId = signal('');
  protected draftStatus: RequestStatus = 'reçue';
  protected draftAssigned = '';
  protected draftNotes = '';
  protected readonly filteredRequests = computed(() => this.admin.serviceRequests().filter((request) => (this.filterType() === 'all' || request.serviceType === this.filterType()) && (this.filterStatus() === 'all' || request.status === this.filterStatus())));
  protected readonly selectedRequest = computed(() => this.admin.serviceRequests().find((request) => request.id === this.selectedId()) ?? null);

  protected select(request: { id: string; status: RequestStatus; assignedTo?: string; notes?: string }): void { this.selectedId.set(request.id); this.draftStatus = request.status; this.draftAssigned = request.assignedTo ?? ''; this.draftNotes = request.notes ?? ''; }
  protected async save(request: { id: string }): Promise<void> { await this.admin.updateServiceRequest(request.id, this.draftStatus, this.draftAssigned, this.draftNotes); }
  protected async prepareNotification(request: { id: string; clientName: string; description: string }): Promise<void> { await this.admin.prepareNotification('service', request.id, `Bonjour ${request.clientName}, votre demande « ${request.description} » est suivie par RHEODYCE.`); }
  protected serviceIcon(type: ServiceType): string { return type === 'maintenance' ? '⌁' : type === 'decoration' ? '✦' : type === 'juridique' ? '§' : '↗'; }
  protected statusClass(status: RequestStatus): string { return status === 'terminée' ? 'bg-[#edf5d6] text-[#657b18]' : status === 'annulée' ? 'bg-[#fff0f0] text-[#b42318]' : status === 'assignée' ? 'bg-[#eee9fb] text-[#7050a2]' : 'bg-[#fff4d9] text-[#946200]'; }
}
