import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { PropertySubmissionService } from '../../core/services/property-submission.service';
import { AuthService } from '../../core/services/auth.service';
import { PropertySubmissionStatus } from '../../shared/models/property-submission.model';

@Component({ selector: 'app-my-property-submissions', standalone: true, imports: [CommonModule, RouterLink], template: `
<section class="bg-rheo-bg pb-20 pt-28"><div class="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><header class="flex flex-col justify-between gap-5 border-b border-rheo-border pb-8 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold uppercase tracking-[.22em] text-rheo-muted">Mes demandes</p><h1 class="mt-3 text-4xl font-semibold tracking-tight text-rheo-dark">Mes annonces proposées.</h1><p class="mt-3 text-sm text-rheo-muted">Suivez la validation et les messages de l’équipe RHEODYCE.</p></div><a routerLink="/location-vente/creer-annonce" class="rounded-xl bg-rheo-accent px-5 py-3 text-sm font-bold">Créer une annonce</a></header>
@if (!auth.isAuthenticated()) { <div class="mt-8 rounded-3xl bg-white p-8 text-center"><a routerLink="/connexion" class="font-semibold">Connectez-vous pour voir vos annonces</a></div> } @else if (service.isLoading()) { <p class="mt-8 rounded-2xl bg-white p-6 text-rheo-muted">Chargement…</p> } @else { @if (service.notifications().length) { <div class="mt-8 grid gap-3">@for (notification of service.notifications(); track notification.id) { <div class="rounded-2xl border border-[#dce8b6] bg-[#f7fbe9] p-4 text-sm"><strong>RHEODYCE · {{ notification.createdAt | date:'dd/MM/yyyy HH:mm' }}</strong><p class="mt-1 text-rheo-muted">{{ notification.message }}</p></div> }</div> } <div class="mt-8 grid gap-4">@for (item of service.submissions(); track item.id) { <article class="rounded-3xl border border-rheo-border bg-white p-6"><div class="flex flex-col justify-between gap-4 sm:flex-row"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-rheo-muted">{{ item.type }} · {{ item.category }} · {{ item.city }}</p><h2 class="mt-2 text-xl font-semibold">{{ item.title }}</h2><p class="mt-2 text-sm text-rheo-muted">Envoyée le {{ item.createdAt | date:'dd/MM/yyyy' }}</p></div><span [class]="statusClass(item.status)" class="h-fit rounded-full px-3 py-1.5 text-xs font-bold">{{ item.status }}</span></div>@if (item.adminMessage) { <p class="mt-5 rounded-xl bg-rheo-bg p-4 text-sm text-rheo-muted"><strong class="text-rheo-dark">Message de l’équipe :</strong> {{ item.adminMessage }}</p> } @if (item.publishedPropertyId) { <a [routerLink]="['/annonces', item.publishedPropertyId]" class="mt-5 inline-flex text-sm font-bold underline">Voir l’annonce publiée →</a> }</article> } @empty { <div class="rounded-3xl bg-white p-10 text-center"><p class="font-semibold">Aucune annonce proposée.</p><a routerLink="/location-vente/creer-annonce" class="mt-4 inline-flex rounded-xl bg-rheo-accent px-5 py-3 text-sm font-bold">Créer une annonce</a></div> }</div> }</div></section>` })
export class MyPropertySubmissionsPage implements OnInit { protected readonly service = inject(PropertySubmissionService); protected readonly auth = inject(AuthService); async ngOnInit(): Promise<void> { await this.service.loadMine(); } protected statusClass(status: PropertySubmissionStatus): string { return status === 'publiée' ? 'bg-[#edf5d6] text-[#557114]' : status === 'refusée' ? 'bg-red-50 text-red-700' : status === 'informations requises' ? 'bg-amber-50 text-amber-700' : 'bg-[#eef1ee] text-rheo-muted'; } }
